# Generated by Django 5.0.6 on 2026-06-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('accuracy', models.FloatField(default=0.0)),
                ('auc', models.FloatField(default=0.0)),
                ('n_samples', models.PositiveIntegerField(default=0)),
                ('n_candidates', models.PositiveIntegerField(default=0)),
                ('positives', models.PositiveIntegerField(default=0)),
                ('negatives', models.PositiveIntegerField(default=0)),
                ('feature_importances', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
    ]
