# Generated by Django 6.0.3 on 2026-07-09 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_indexes'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_candida_5376b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_candida_605826_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='candidate',
            new_name='recipient',
        ),
        migrations.AlterField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='match_data',
            field=models.JSONField(blank=True, default=dict, help_text='reasons, matched_skills, missing_skills, explanation_summary, etc'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('job_match', 'Job Match'), ('high_priority', 'High Priority Match'), ('recruiter_alert', 'Recruiter Alert'), ('status_update', 'Application Status Update'), ('new_application', 'New Application'), ('profile_updated', 'Profile/Resume Updated')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'job'], name='notificatio_recipie_263b4c_idx'),
        ),
    ]
