# Generated by Django 5.2.15 on 2026-06-10 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0002_job_requirements_salary'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='achievement_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='ats_score',
            field=models.PositiveIntegerField(default=0, help_text='ATS compatibility 0-100'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('2_weeks', '2 Weeks'), ('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months')], max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='career_objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Comma-separated certifications'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='college',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='district',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='expected_salary_max',
            field=models.PositiveIntegerField(blank=True, help_text='NPR/month', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='expected_salary_min',
            field=models.PositiveIntegerField(blank=True, help_text='NPR/month', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='hiring_probability',
            field=models.FloatField(default=0.0, help_text='Predicted hire probability 0-1'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='industry_interest',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='languages',
            field=models.TextField(blank=True, help_text='Comma-separated spoken languages'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='preferred_role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='province',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='research_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='soft_skills',
            field=models.TextField(blank=True, help_text='Comma-separated soft skills'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='university',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='volunteer_experience',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ATSAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.PositiveIntegerField(default=0)),
                ('completeness_score', models.PositiveIntegerField(default=0)),
                ('formatting_score', models.PositiveIntegerField(default=0)),
                ('keyword_score', models.PositiveIntegerField(default=0)),
                ('experience_score', models.PositiveIntegerField(default=0)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('section_scores', models.JSONField(default=dict)),
                ('missing_sections', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ats_analysis', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.TextField(help_text='JSON-encoded float list')),
                ('model_name', models.CharField(default='all-MiniLM-L6-v2', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_roles', models.JSONField(default=list, help_text='[{"role":"Backend Dev","confidence":0.87,"reason":"..."}]')),
                ('learning_paths', models.JSONField(default=list, help_text='[{"skill":"Docker","priority":"high","resources":["..."]}]')),
                ('top_role', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_recommendation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillGapReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_skills', models.JSONField(default=list)),
                ('missing_technologies', models.JSONField(default=list)),
                ('missing_certifications', models.JSONField(default=list)),
                ('experience_gaps', models.JSONField(default=list)),
                ('matched_skills', models.JSONField(default=list)),
                ('match_improvement_pct', models.FloatField(default=0.0, help_text='Estimated % score improvement if gaps filled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
