# Generated by Django 5.0.6 on 2026-06-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidateprofile_achievement_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='avatar',
            field=models.FileField(blank=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='logo',
            field=models.FileField(blank=True, upload_to='logos/'),
        ),
    ]
