# Generated by Django 5.2.15 on 2026-07-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_candidateprofile_avatar_employerprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Set when the user confirms their address via the verification link.'),
        ),
    ]
